### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by Globerada** [shetabit/extractor#1]
Add a method onto RequestAbtract to be able to add a proxy. Also, have the choice to set verify = false.

**Comment by khanzadimahdi** [comment]
you can add this feature and create pull request.
i will merge it.

**Comment by Globerada** [comment]
Ok, I will do it.
Also I want to confirm with you that the way you add query string is not very useful if you pass the full URI.

If you pass the full URI, with query params, you are overwriting into getOptions() with an empty string. We should check if it is empty to not overwrite the URI that the user can have passed.

What do you think?

**Comment by khanzadimahdi** [comment]
i think we should parse given URI and extract query strings, then we can append them into `getOptions()`.
i will be happy if you solve these bugs.
solve them by your pull requests.
